sudo: false
language: node_js
node_js:
  - "7"
  - "6"
before_script:
  - npm prune

script:
  - make build
  - make lint
  - make test-cov

after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
